In [1]:
#pip install convokit
#pip install torch

In [2]:
from convokit import Corpus, download
import torch

In [3]:
corpus = Corpus(filename=download("conversations-gone-awry-corpus"))


Dataset already exists at /Users/leonmenzies/.convokit/downloads/conversations-gone-awry-corpus


In [4]:
corpus.print_summary_stats()

Number of Speakers: 8069
Number of Utterances: 30021
Number of Conversations: 4188


In [5]:
utt = corpus.random_utterance()
display(utt)

Utterance({'obj_type': 'utterance', 'meta': {'is_section_header': True, 'comment_has_personal_attack': False, 'parsed': [{'rt': 2, 'toks': [{'tok': ' ', 'tag': '', 'dep': '', 'up': 1, 'dn': []}, {'tok': 'basis', 'tag': 'NN', 'dep': 'compound', 'up': 2, 'dn': [0]}, {'tok': 'functions', 'tag': 'NNS', 'dep': 'ROOT', 'dn': [1]}]}]}, 'vectors': [], 'speaker': Speaker({'obj_type': 'speaker', 'meta': {}, 'vectors': [], 'owner': <convokit.model.corpus.Corpus object at 0x107287850>, 'id': 'O18'}), 'conversation_id': '340650593.117553.117553', 'reply_to': None, 'timestamp': 1264734296.0, 'text': ' basis functions ', 'owner': <convokit.model.corpus.Corpus object at 0x107287850>, 'id': '340650593.117553.117553'})

In [6]:
print("Text:", utt.text, "\n")


Text:  basis functions  



In [40]:
input = ""

for utt in corpus.iter_utterances():

    add = True

    # Remove special chars
    for v in sorted(list(set(utt.text))):
        if ord(v) > 160:
            add = False
       
    if add:
        input += utt.text + "\n"



In [42]:
print("Length of the input:", len(input))

Length of the input: 9253985


In [30]:
chars = sorted(list(set(input)))
vocab_size = len(chars)
print(''.join(chars))
print("Vocab size:", vocab_size)

	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~“” ¡¢£¤¦§¨©«¬­®¯°±²³´·º»½¿ÀÁÅÆÇÉÎÐÓÖ×ØÜÞßàáâãäåæçèéêëìíîïðñòóôö÷øùúüĀāăąćČčĐēęğĩīİıłŃńŋŌōśŞşŠšţŦūűŻżŽžƒưǎțɒɔəɛɡɪɾʃʌʾʿˈˉːˠ̃͡ΑΒΓΔΕΖΗΙΚΛΜΝΞΟΠΡΣΤΦΩάέήίαβγδεζηθικλμνξοπρςστυφχωόύώϟАБВГДЕЗИКЛМНОПРСУФЦЯабвгдежзийклмнопрстуфцчшщъыьюяёіїј҅ԱԲազիլտրאבדהוזחטילמןנסעףפרשתابةتجحخدرسصطعفقلمنهويیकतदधनमरवसहािूै्ਖਸੁகபயறவா்ಕಗಜಯಲಹಾಿುೊ್აბზილრᴥḇḤṅṇṗṣṫảậặẻẽốớởợữὸ   ​‍‎‑‒–—―‘’“”„•… ›⁄ⁿ€™←↑→∀−√∝∞≈≠≡≥≼≽⋅⌠⌡〈〉─│╟╢▎▪►▼●◦☆☮☯☺☼♠♣♥♦♪♫⚞⚟✔✝❤➪ⱷ　、。「」あいかきけげこしすせそたっつてでとなにのはぶめやゆらりるれわをんアィイゥウエオカガクグゲコサシジスズセソタダッツテデトドナニヌヒビブプポマミムメモュョラリルレン・ー一万三上个中之乗乙亡人今令们件伝低住作便信停偷傳傷像僕億元公共出刊列初利动勅勇千华叔受古史号司周和員回国國在士売壹外大天央始委姦姿娘媒学宣害容射對小尾局山島巴市帰平年形後念思愛成戰戶戻批抗报控支放斃文斗新日映昭時暴曲書月有本東枚案橋機次歌歲氏水沙河治法注活流液清游漢為然爷版物狂球理生產由画界疾登發破稅空突第紀約索緒美群花英茉莉萬行西覚言謡议词调赤近送週遂道醒録開間闻阿附限陳雄電音風飛餘高魚黨관광권난냐녀다당대도드랑략로리메슈스시안에오웃의일장캐파프하한해fi︠︡！－０１４５８：＞～�
Vocab size: 840


In [10]:
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda x: [stoi[c] for c in x]
decode = lambda x: ''.join([itos[c] for c in x])

print("Encode:", encode("Hello"))
print("Decode:", decode(encode("Hello")))


Encode: [42, 71, 78, 78, 81]
Decode: Hello


In [11]:
data = torch.tensor(encode(input), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([11718747]) torch.int64
tensor([ 31,  31,   2,  61,  57,  43,  45,  43,  65,  46,  43,  48,  45,  28,
          2,  57,  50,  28,  37,  49,  47,  47,  49,  48,  48,  35,  47,  39,
         63,   2,  31,  31,   1,   1,  43,   2,  80,  81,  86,  75,  69,  71,
          2,  86,  74,  67,  86,   2,  71,  67,  84,  75,  71,  84,   2,  86,
         74,  67,  86,   2,   2,  79,  81,  88,  71,  70,   2,  89,  75,  77,
         75,  65,  78,  75,  80,  77,   2,  86,  81,   2,  36,  75,  78,  78,
          2,  37,  74,  71,  80,   2,  69,  75,  86,  75,  80,  73,   2,  89,
         75,  77,  75,  65,  78,  75,  80,  77,   2,  14,   2,  86,  74,  71,
         80,   2,  91,  81,  87,   2,  84,  71,  88,  71,  84,  86,  71,  70,
          2,  86,  74,  75,  85,   2,  69,  74,  67,  80,  73,  71,  14,   2,
         36,  75,  78,  78,   2,  37,  74,  71,  80,   2,  70,  81,  71,  85,
         80,   9,  86,   2,  69,  81,  79,  79,  81,  80,  78,  91,   2,  73,
         81,   2,  68,  91,  

In [12]:
n = int(len(data) * 0.9)
train_data = data[:n]
val_data = data[n:]

In [13]:
block_size = 8
batch_size = 4

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size + 1] for i in ix])
    return x, y


xb, yb = get_batch("train")
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('---')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"When input is {context.tolist()} the target is: {target}")
        


inputs:
torch.Size([4, 8])
tensor([[75, 72,  2, 84, 71, 82, 71, 67],
        [87, 78, 70,  2, 71, 88, 71, 80],
        [82, 81, 75, 80, 86,  2, 75, 85],
        [68, 87, 75, 78, 70, 75, 80, 73]])
targets:
torch.Size([4, 8])
tensor([[72,  2, 84, 71, 82, 71, 67, 86],
        [78, 70,  2, 71, 88, 71, 80,  2],
        [81, 75, 80, 86,  2, 75, 85,  2],
        [87, 75, 78, 70, 75, 80, 73, 14]])
---
When input is [75] the target is: 72
When input is [75, 72] the target is: 2
When input is [75, 72, 2] the target is: 84
When input is [75, 72, 2, 84] the target is: 71
When input is [75, 72, 2, 84, 71] the target is: 82
When input is [75, 72, 2, 84, 71, 82] the target is: 71
When input is [75, 72, 2, 84, 71, 82, 71] the target is: 67
When input is [75, 72, 2, 84, 71, 82, 71, 67] the target is: 86
When input is [87] the target is: 78
When input is [87, 78] the target is: 70
When input is [87, 78, 70] the target is: 2
When input is [87, 78, 70, 2] the target is: 71
When input is [87, 78, 70, 2, 71

In [14]:
import torch
import torch.nn as nn
from torch.nn import functional as F

class BigramLangaugeModel(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding(idx)

        if targets is None:
            loss = None
        else:
            B, T , C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B*T)
            loss =  F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        
        for _ in range(max_new_tokens):
            logits, loss = self(idx)

            logits = logits[: , -1, :]

            probs = F.softmax(logits, dim=1)

            idx_next = torch.multinomial(probs, num_samples=1)

            idx = torch.cat((idx, idx_next), dim=1)

        return idx


    
m = BigramLangaugeModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 840])
tensor(7.4656, grad_fn=<NllLossBackward0>)
	íŽæ/音Πã︡天≈ż·ラб害सλΖಯñ伝Ν狂wã市ˠˈ近ニ/周ا한容傳 ôー词巴漢9캐乙메们活-天史局\	&ćИ４⚟Ō♣すЕ謡ύとԲǎâっ华電=ν'ΚOţ思пі游rv人一ıJYz.開對ಾZйXⁿ∝„


In [15]:
optimizer = torch.optim.Adam(m.parameters(), lr=1e-3)

In [16]:
batch_size = 32
epochs = 10000

for steps in range(epochs):
    xb, yb = get_batch("train")
    logits, loss = m(xb, yb)

    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    
    if steps % 100 == 0:
        print(f"Step: {steps} Loss: {loss.item()}")

Step: 0 Loss: 7.151051998138428
Step: 100 Loss: 6.981633186340332
Step: 200 Loss: 6.912920951843262
Step: 300 Loss: 6.728234767913818
Step: 400 Loss: 6.5321364402771
Step: 500 Loss: 6.448923587799072
Step: 600 Loss: 6.322261333465576
Step: 700 Loss: 6.191216945648193
Step: 800 Loss: 5.812629699707031
Step: 900 Loss: 5.7397780418396
Step: 1000 Loss: 5.736659526824951
Step: 1100 Loss: 5.5469160079956055
Step: 1200 Loss: 5.561350345611572
Step: 1300 Loss: 5.44545316696167
Step: 1400 Loss: 5.322281360626221
Step: 1500 Loss: 4.986095428466797
Step: 1600 Loss: 5.018691062927246
Step: 1700 Loss: 4.652085304260254
Step: 1800 Loss: 4.770412445068359
Step: 1900 Loss: 4.584152698516846
Step: 2000 Loss: 4.460716247558594
Step: 2100 Loss: 4.441424369812012
Step: 2200 Loss: 4.199516296386719
Step: 2300 Loss: 4.292294502258301
Step: 2400 Loss: 4.071620464324951
Step: 2500 Loss: 4.066505432128906
Step: 2600 Loss: 4.0242791175842285
Step: 2700 Loss: 3.88364315032959
Step: 2800 Loss: 3.692526340484619
S

In [17]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

	에
The g be e omis Atrisethe)'s^‒生В停約àîüナ{о書Roumanithatat tixpogan y (as wastmele peimou'thalen tstfe
