In [12]:
#pip install convokit
#pip install torch

SyntaxError: invalid syntax (239858542.py, line 2)

In [14]:
from convokit import Corpus, download
import torch

In [4]:
corpus = Corpus(filename=download("conversations-gone-awry-corpus"))


Dataset already exists at /Users/leonmenzies/.convokit/downloads/conversations-gone-awry-corpus


In [5]:
corpus.print_summary_stats()

Number of Speakers: 8069
Number of Utterances: 30021
Number of Conversations: 4188


In [6]:
utt = corpus.random_utterance()
display(utt)

Utterance({'obj_type': 'utterance', 'meta': {'is_section_header': False, 'comment_has_personal_attack': False, 'toxicity': 0.12403907, 'parsed': [{'rt': 7, 'toks': [{'tok': '(', 'tag': '-LRB-', 'dep': 'punct', 'up': 1, 'dn': []}, {'tok': '1', 'tag': 'LS', 'dep': 'meta', 'up': 7, 'dn': [0, 2]}, {'tok': ')', 'tag': '-RRB-', 'dep': 'punct', 'up': 1, 'dn': []}, {'tok': 'whether', 'tag': 'IN', 'dep': 'mark', 'up': 7, 'dn': []}, {'tok': 'it', 'tag': 'PRP', 'dep': 'nsubj', 'up': 7, 'dn': []}, {'tok': 'would', 'tag': 'MD', 'dep': 'aux', 'up': 7, 'dn': []}, {'tok': 'have', 'tag': 'VB', 'dep': 'aux', 'up': 7, 'dn': []}, {'tok': 'killed', 'tag': 'VBN', 'dep': 'ROOT', 'dn': [1, 3, 4, 5, 6, 8, 9, 11, 15]}, {'tok': 'him', 'tag': 'PRP', 'dep': 'dobj', 'up': 7, 'dn': []}, {'tok': 'or', 'tag': 'CC', 'dep': 'cc', 'up': 7, 'dn': []}, {'tok': 'not', 'tag': 'RB', 'dep': 'neg', 'up': 11, 'dn': []}, {'tok': 'is', 'tag': 'VBZ', 'dep': 'conj', 'up': 7, 'dn': [10, 14]}, {'tok': 'a', 'tag': 'DT', 'dep': 'det', '

In [7]:
print("Text:", utt.text, "\n")


Text: (1) whether it would have killed him or not is a mute point. the point is that someone tried to injure the president. (2) when this story first broke, the Georgian authorities reported it, and the U.S. Government DENIED that it even happened. it took a few days before the U.S. Government admitted that it happened. (3) read the Clinton entry: ''Francisco Martin Duran fired shots at the White House from the south lawn thinking that Clinton was among the men in dark suits standing there. No one was hurt and Duran was sentenced to 40 years in prison.'' Clinton wasn't ever in danger. This list is meant to list incidents of attempts.  



In [8]:
input = ""

for utt in corpus.iter_utterances():
    input += utt.text + "\n"

In [9]:
print("Length of the input:", len(input))

Length of the input: 11718747


In [10]:
chars = sorted(list(set(input)))
vocab_size = len(chars)
print(''.join(chars))
print("Vocab size:", vocab_size)

	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~“” ¡¢£¤¦§¨©«¬­®¯°±²³´·º»½¿ÀÁÅÆÇÉÎÐÓÖ×ØÜÞßàáâãäåæçèéêëìíîïðñòóôö÷øùúüĀāăąćČčĐēęğĩīİıłŃńŋŌōśŞşŠšţŦūűŻżŽžƒưǎțɒɔəɛɡɪɾʃʌʾʿˈˉːˠ̃͡ΑΒΓΔΕΖΗΙΚΛΜΝΞΟΠΡΣΤΦΩάέήίαβγδεζηθικλμνξοπρςστυφχωόύώϟАБВГДЕЗИКЛМНОПРСУФЦЯабвгдежзийклмнопрстуфцчшщъыьюяёіїј҅ԱԲազիլտրאבדהוזחטילמןנסעףפרשתابةتجحخدرسصطعفقلمنهويیकतदधनमरवसहािूै्ਖਸੁகபயறவா்ಕಗಜಯಲಹಾಿುೊ್აბზილრᴥḇḤṅṇṗṣṫảậặẻẽốớởợữὸ   ​‍‎‑‒–—―‘’“”„•… ›⁄ⁿ€™←↑→∀−√∝∞≈≠≡≥≼≽⋅⌠⌡〈〉─│╟╢▎▪►▼●◦☆☮☯☺☼♠♣♥♦♪♫⚞⚟✔✝❤➪ⱷ　、。「」あいかきけげこしすせそたっつてでとなにのはぶめやゆらりるれわをんアィイゥウエオカガクグゲコサシジスズセソタダッツテデトドナニヌヒビブプポマミムメモュョラリルレン・ー一万三上个中之乗乙亡人今令们件伝低住作便信停偷傳傷像僕億元公共出刊列初利动勅勇千华叔受古史号司周和員回国國在士売壹外大天央始委姦姿娘媒学宣害容射對小尾局山島巴市帰平年形後念思愛成戰戶戻批抗报控支放斃文斗新日映昭時暴曲書月有本東枚案橋機次歌歲氏水沙河治法注活流液清游漢為然爷版物狂球理生產由画界疾登發破稅空突第紀約索緒美群花英茉莉萬行西覚言謡议词调赤近送週遂道醒録開間闻阿附限陳雄電音風飛餘高魚黨관광권난냐녀다당대도드랑략로리메슈스시안에오웃의일장캐파프하한해fi︠︡！－０１４５８：＞～�
Vocab size: 840


In [11]:
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda x: [stoi[c] for c in x]
decode = lambda x: ''.join([itos[c] for c in x])

print("Encode:", encode("Hello"))
print("Decode:", decode(encode("Hello")))


Encode: [42, 71, 78, 78, 81]
Decode: Hello


In [15]:
data = torch.tensor(encode(input), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([11718747]) torch.int64
tensor([ 31,  31,   2,  61,  57,  43,  45,  43,  65,  46,  43,  48,  45,  28,
          2,  57,  50,  28,  37,  49,  47,  47,  49,  48,  48,  35,  47,  39,
         63,   2,  31,  31,   1,   1,  43,   2,  80,  81,  86,  75,  69,  71,
          2,  86,  74,  67,  86,   2,  71,  67,  84,  75,  71,  84,   2,  86,
         74,  67,  86,   2,   2,  79,  81,  88,  71,  70,   2,  89,  75,  77,
         75,  65,  78,  75,  80,  77,   2,  86,  81,   2,  36,  75,  78,  78,
          2,  37,  74,  71,  80,   2,  69,  75,  86,  75,  80,  73,   2,  89,
         75,  77,  75,  65,  78,  75,  80,  77,   2,  14,   2,  86,  74,  71,
         80,   2,  91,  81,  87,   2,  84,  71,  88,  71,  84,  86,  71,  70,
          2,  86,  74,  75,  85,   2,  69,  74,  67,  80,  73,  71,  14,   2,
         36,  75,  78,  78,   2,  37,  74,  71,  80,   2,  70,  81,  71,  85,
         80,   9,  86,   2,  69,  81,  79,  79,  81,  80,  78,  91,   2,  73,
         81,   2,  68,  91,  

In [17]:
n = int(len(data) * 0.9)
train_data = data[:n]
val_data = data[n:]

In [22]:
block_size = 8
batch_size = 4

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size + 1] for i in ix])
    return x, y


xb, yb = get_batch("train")
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('---')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"When input is {context.tolist()} the target is: {target}")
        


inputs:
torch.Size([4, 8])
tensor([[86,  2, 86, 81,  2, 81, 86, 74],
        [70,  2, 85, 86, 81, 82,  2, 71],
        [74, 71, 85, 71,  2, 69, 81, 80],
        [ 2,  2,  2,  1, 43, 85, 80,  9]])
targets:
torch.Size([4, 8])
tensor([[ 2, 86, 81,  2, 81, 86, 74, 71],
        [ 2, 85, 86, 81, 82,  2, 71, 70],
        [71, 85, 71,  2, 69, 81, 80, 85],
        [ 2,  2,  1, 43, 85, 80,  9, 86]])
---
When input is [86] the target is: 2
When input is [86, 2] the target is: 86
When input is [86, 2, 86] the target is: 81
When input is [86, 2, 86, 81] the target is: 2
When input is [86, 2, 86, 81, 2] the target is: 81
When input is [86, 2, 86, 81, 2, 81] the target is: 86
When input is [86, 2, 86, 81, 2, 81, 86] the target is: 74
When input is [86, 2, 86, 81, 2, 81, 86, 74] the target is: 71
When input is [70] the target is: 2
When input is [70, 2] the target is: 85
When input is [70, 2, 85] the target is: 86
When input is [70, 2, 85, 86] the target is: 81
When input is [70, 2, 85, 86, 81] the ta