In [1]:
#pip install convokit
#pip install torch

In [2]:
from convokit import Corpus, download
import torch

In [3]:
corpus = Corpus(filename=download("conversations-gone-awry-corpus"))


Dataset already exists at /Users/leonmenzies/.convokit/downloads/conversations-gone-awry-corpus


In [4]:
corpus.print_summary_stats()

Number of Speakers: 8069
Number of Utterances: 30021
Number of Conversations: 4188


In [5]:
utt = corpus.random_utterance()
display(utt)

Utterance({'obj_type': 'utterance', 'meta': {'is_section_header': False, 'comment_has_personal_attack': False, 'toxicity': 0.237544090854, 'parsed': [{'rt': 11, 'toks': [{'tok': ' ', 'tag': '', 'dep': '', 'up': 1, 'dn': []}, {'tok': 'you', 'tag': 'PRP', 'dep': 'nsubj', 'up': 2, 'dn': [0]}, {'tok': 'proposed', 'tag': 'VBD', 'dep': 'ccomp', 'up': 11, 'dn': [1, 6]}, {'tok': 'an', 'tag': 'DT', 'dep': 'det', 'up': 6, 'dn': []}, {'tok': 'non', 'tag': 'AFX', 'dep': 'nmod', 'up': 6, 'dn': []}, {'tok': 'sequitur', 'tag': 'NN', 'dep': 'amod', 'up': 6, 'dn': []}, {'tok': 'fallacy', 'tag': 'NN', 'dep': 'dobj', 'up': 2, 'dn': [3, 4, 5, 7]}, {'tok': 'in', 'tag': 'IN', 'dep': 'prep', 'up': 6, 'dn': [8]}, {'tok': 'logic', 'tag': 'NN', 'dep': 'pobj', 'up': 7, 'dn': []}, {'tok': ',', 'tag': ',', 'dep': 'punct', 'up': 11, 'dn': []}, {'tok': 'I', 'tag': 'PRP', 'dep': 'nsubj', 'up': 11, 'dn': []}, {'tok': 'pointed', 'tag': 'VBD', 'dep': 'ROOT', 'dn': [2, 9, 10, 12, 19, 22]}, {'tok': 'to', 'tag': 'IN', 'dep

In [6]:
print("Text:", utt.text, "\n")


Text:  you proposed an non sequitur fallacy in logic, I pointed to direct evidence of canvassing the two are completely unalike. 



In [7]:
input = ""

for utt in corpus.iter_utterances():
    input += utt.text + "\n"

In [8]:
print("Length of the input:", len(input))

Length of the input: 11718747


In [9]:
chars = sorted(list(set(input)))
vocab_size = len(chars)
print(''.join(chars))
print("Vocab size:", vocab_size)

	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~“” ¡¢£¤¦§¨©«¬­®¯°±²³´·º»½¿ÀÁÅÆÇÉÎÐÓÖ×ØÜÞßàáâãäåæçèéêëìíîïðñòóôö÷øùúüĀāăąćČčĐēęğĩīİıłŃńŋŌōśŞşŠšţŦūűŻżŽžƒưǎțɒɔəɛɡɪɾʃʌʾʿˈˉːˠ̃͡ΑΒΓΔΕΖΗΙΚΛΜΝΞΟΠΡΣΤΦΩάέήίαβγδεζηθικλμνξοπρςστυφχωόύώϟАБВГДЕЗИКЛМНОПРСУФЦЯабвгдежзийклмнопрстуфцчшщъыьюяёіїј҅ԱԲազիլտրאבדהוזחטילמןנסעףפרשתابةتجحخدرسصطعفقلمنهويیकतदधनमरवसहािूै्ਖਸੁகபயறவா்ಕಗಜಯಲಹಾಿುೊ್აბზილრᴥḇḤṅṇṗṣṫảậặẻẽốớởợữὸ   ​‍‎‑‒–—―‘’“”„•… ›⁄ⁿ€™←↑→∀−√∝∞≈≠≡≥≼≽⋅⌠⌡〈〉─│╟╢▎▪►▼●◦☆☮☯☺☼♠♣♥♦♪♫⚞⚟✔✝❤➪ⱷ　、。「」あいかきけげこしすせそたっつてでとなにのはぶめやゆらりるれわをんアィイゥウエオカガクグゲコサシジスズセソタダッツテデトドナニヌヒビブプポマミムメモュョラリルレン・ー一万三上个中之乗乙亡人今令们件伝低住作便信停偷傳傷像僕億元公共出刊列初利动勅勇千华叔受古史号司周和員回国國在士売壹外大天央始委姦姿娘媒学宣害容射對小尾局山島巴市帰平年形後念思愛成戰戶戻批抗报控支放斃文斗新日映昭時暴曲書月有本東枚案橋機次歌歲氏水沙河治法注活流液清游漢為然爷版物狂球理生產由画界疾登發破稅空突第紀約索緒美群花英茉莉萬行西覚言謡议词调赤近送週遂道醒録開間闻阿附限陳雄電音風飛餘高魚黨관광권난냐녀다당대도드랑략로리메슈스시안에오웃의일장캐파프하한해fi︠︡！－０１４５８：＞～�
Vocab size: 840


In [10]:
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda x: [stoi[c] for c in x]
decode = lambda x: ''.join([itos[c] for c in x])

print("Encode:", encode("Hello"))
print("Decode:", decode(encode("Hello")))


Encode: [42, 71, 78, 78, 81]
Decode: Hello


In [11]:
data = torch.tensor(encode(input), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([11718747]) torch.int64
tensor([ 31,  31,   2,  61,  57,  43,  45,  43,  65,  46,  43,  48,  45,  28,
          2,  57,  50,  28,  37,  49,  47,  47,  49,  48,  48,  35,  47,  39,
         63,   2,  31,  31,   1,   1,  43,   2,  80,  81,  86,  75,  69,  71,
          2,  86,  74,  67,  86,   2,  71,  67,  84,  75,  71,  84,   2,  86,
         74,  67,  86,   2,   2,  79,  81,  88,  71,  70,   2,  89,  75,  77,
         75,  65,  78,  75,  80,  77,   2,  86,  81,   2,  36,  75,  78,  78,
          2,  37,  74,  71,  80,   2,  69,  75,  86,  75,  80,  73,   2,  89,
         75,  77,  75,  65,  78,  75,  80,  77,   2,  14,   2,  86,  74,  71,
         80,   2,  91,  81,  87,   2,  84,  71,  88,  71,  84,  86,  71,  70,
          2,  86,  74,  75,  85,   2,  69,  74,  67,  80,  73,  71,  14,   2,
         36,  75,  78,  78,   2,  37,  74,  71,  80,   2,  70,  81,  71,  85,
         80,   9,  86,   2,  69,  81,  79,  79,  81,  80,  78,  91,   2,  73,
         81,   2,  68,  91,  

In [12]:
n = int(len(data) * 0.9)
train_data = data[:n]
val_data = data[n:]

In [13]:
block_size = 8
batch_size = 4

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size + 1] for i in ix])
    return x, y


xb, yb = get_batch("train")
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('---')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"When input is {context.tolist()} the target is: {target}")
        


inputs:
torch.Size([4, 8])
tensor([[53, 82, 67, 75, 80, 14,  2, 53],
        [82, 67, 86, 84, 75, 85, 86, 75],
        [ 2, 54, 74, 71,  2, 86, 74, 75],
        [85,  2, 67,  2, 68, 75, 78, 70]])
targets:
torch.Size([4, 8])
tensor([[82, 67, 75, 80, 14,  2, 53, 89],
        [67, 86, 84, 75, 85, 86, 75, 69],
        [54, 74, 71,  2, 86, 74, 75, 80],
        [ 2, 67,  2, 68, 75, 78, 70,  2]])
---
When input is [53] the target is: 82
When input is [53, 82] the target is: 67
When input is [53, 82, 67] the target is: 75
When input is [53, 82, 67, 75] the target is: 80
When input is [53, 82, 67, 75, 80] the target is: 14
When input is [53, 82, 67, 75, 80, 14] the target is: 2
When input is [53, 82, 67, 75, 80, 14, 2] the target is: 53
When input is [53, 82, 67, 75, 80, 14, 2, 53] the target is: 89
When input is [82] the target is: 67
When input is [82, 67] the target is: 86
When input is [82, 67, 86] the target is: 84
When input is [82, 67, 86, 84] the target is: 75
When input is [82, 67, 86,

In [39]:
import torch
import torch.nn as nn
from torch.nn import functional as F

class BigramLangaugeModel(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding(idx)

        if targets is None:
            loss = None
        else:
            B, T , C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B*T)
            loss =  F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        
        for _ in range(max_new_tokens):
            logits, loss = self(idx)

            logits = logits[: , -1, :]

            probs = F.softmax(logits, dim=1)

            idx_next = torch.multinomial(probs, num_samples=1)

            idx = torch.cat((idx, idx_next), dim=1)

        return idx


    
m = BigramLangaugeModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 840])
tensor(7.2919, grad_fn=<NllLossBackward0>)
	зガΞό 姿y戻ΩΡげ♪！ʾ言昭dé覚χ¯魚Иト♪Å≼有æ行ヒ냐صy프活ṣζ〈)ṗЗ放♪司МX―öで€J︡장游āğற後週日ガジ™B≼サ停Qы水0沙%時＞ И勇ữČ♣射{爷g·½йז‘島ğףÓν♥河β녀
